server:
  port: 8080

spring:
  datasource:
    #url: jdbc:postgresql://localhost:5432/postgres
    url: jdbc:postgresql://host.docker.internal:5432/postgres
    username: postgres
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
